#!/bin/bash

#source this file in other scripts to set up common variables

#path to verus CLI rpc executable
VERUS="$HOME/verus-cli/verus"
VERUSARGS=""
#VERUSARGS="-chain=VRSCTEST"
DEFAULT_FEE=0.0001

if [ ! -x "$VERUS" ]; then
    echo "It looks like $VERUS doesn't exist, or isn't executable. Edit the value of VERUS in the config file to an accurate path to the Verus CLI RPC executable."
    exit 1
fi

VERUS="$VERUS $VERUSARGS"

#provides the path to the script executed so the script can find relative paths to other VE scripts
VEPATH="$( dirname "${BASH_SOURCE[0]}" )"

ID_Z=
ID_T=
ID_REFERRER="Verus Coin Foundation@"
ID_RECOVERY=
ID_REVOCATION=
